FROM node:16.18.0-bullseye-slim

ENV NEXT_TELEMETRY_DISABLED 1

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm@7.13.6 \
  && pnpm install --frozen-lockfile

COPY src ./src
COPY public ./public
COPY next.config.js .
COPY tsconfig.json .

CMD ["pnpm", "dev"]