import s from "@/styles/Home.module.css";
import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import useSWR from "swr";

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const date = new Date();
  const currentTime = new Intl.DateTimeFormat("sv-SE", {
    dateStyle: "short",
    timeStyle: "short",
  }).format(date);
  return {
    props: {
      currentTime,
    },
  };
}

type User = {
  name: string;
};

const fetcher = (url: string) => fetch(url).then((r) => r.json());

const useUser = () => {
  const { data, error } = useSWR<User>("/api/hello", fetcher);

  return {
    user: data,
    isLoading: !error && !data,
    isError: error,
  };
};

const UserView = () => {
  const { user, isLoading, isError } = useUser();
  if (isLoading) return <p>loading...</p>;
  if (isError) return <p>error</p>;
  return (
    <p className={s.description} style={{ margin: 0 }}>
      User from api route: <code className={s.code}>{user?.name}</code>
    </p>
  );
};

const Home: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = ({ currentTime }) => {
  return (
    <div className={s.container}>
      <Head>
        <title>Docker + Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <h1 className={s.title}>Docker + Next.js</h1>
        <p className={s.description}>
          Time from server: <code className={s.code}>{currentTime}</code>
        </p>
        <UserView />
      </main>
    </div>
  );
};

export default Home;
